CRITICAL - 2022-08-04 00:41:06 --> Invalid file: nombre_motivos/nuevo.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(41): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->nuevo()
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-08-04 13:51:57 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «fecha_ingreso» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;fecha_ing...
                                                             ^ in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 13:51:57 --> pg_query(): Query failed: ERROR:  no existe la columna «fecha_ingreso» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;fecha_ing...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-08-04 13:57:14 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «created_at» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;created_a...
                                                             ^ in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 13:57:14 --> pg_query(): Query failed: ERROR:  no existe la columna «created_at» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;created_a...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-08-04 13:57:46 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «created_at» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;created_a...
                                                             ^ in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 13:57:46 --> pg_query(): Query failed: ERROR:  no existe la columna «created_at» en la relación «usuarios»
LINE 1: ...RT INTO &quot;visitas&quot;.&quot;usuarios&quot; (&quot;apellido_paterno&quot;, &quot;created_a...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-08-04 13:58:34 --> ErrorException: pg_query(): Query failed: ERROR:  el valor nulo en la columna «apellido_materno» de la relación «usuarios» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (8, Saldivar, null, null, null, null, null, null, 1). in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 13:58:34 --> pg_query(): Query failed: ERROR:  el valor nulo en la columna «apellido_materno» de la relación «usuarios» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (8, Saldivar, null, null, null, null, null, null, 1).
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(52): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-08-04 14:26:38 --> ErrorException: pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «uq_numero_identificador»
DETAIL:  Ya existe la llave (numero_identificador)=(302320679). in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(56): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 14:26:38 --> pg_query(): Query failed: ERROR:  llave duplicada viola restricción de unicidad «uq_numero_identificador»
DETAIL:  Ya existe la llave (numero_identificador)=(302320679).
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(56): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-08-04 14:38:44 --> ErrorException: pg_query(): Query failed: ERROR:  el valor «8373764837» está fuera de rango para el tipo integer
LINE 1: ...rera_area&quot;) VALUES ('Saldivar ', 'Rueda', 'Luis', '837376483...
                                                             ^ in C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(58): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 14:38:44 --> pg_query(): Query failed: ERROR:  el valor «8373764837» está fuera de rango para el tipo integer
LINE 1: ...rera_area&quot;) VALUES ('Saldivar ', 'Rueda', 'Luis', '837376483...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\visitas\system\Database\Postgre\Connection.php(135): pg_query(Object(PgSql\Connection), 'INSERT INTO "vi...')
#2 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "vi...')
#3 C:\xampp\htdocs\visitas\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "vi...')
#4 C:\xampp\htdocs\visitas\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "vi...', Array, false)
#5 C:\xampp\htdocs\visitas\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\visitas\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\visitas\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\visitas\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\visitas\app\Controllers\Visitantes.php(58): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Visitantes->insertar()
#11 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Visitantes))
#12 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-08-04 17:04:41 --> Invalid file: nombre_motivos/nuevo.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(41): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->nuevo()
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-08-04 17:08:29 --> Invalid file: nombre_motivos/eliminados.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(33): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->eliminados()
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-08-04 17:16:13 --> Invalid file: nombre_motivos/nuevo.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(41): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->nuevo()
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-08-04 17:31:36 --> Undefined variable $motivos
#0 C:\xampp\htdocs\visitas\app\Views\nombre_motivos\nuevo.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\visitas\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\visitas\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#4 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(41): view('nombre_motivos/...', Array)
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->nuevo()
#6 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#7 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-08-04 17:59:44 --> Undefined property: App\Controllers\Nombre_motivos::$visitantes
#0 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 50)
#1 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->insertar()
#2 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-08-04 18:45:26 --> Undefined property: App\Controllers\Nombre_motivos::$visitantes
#0 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 50)
#1 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->insertar()
#2 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-08-04 22:36:03 --> Undefined property: App\Controllers\Nombre_motivos::$visitantes
#0 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 50)
#1 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->insertar()
#2 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-08-04 22:42:49 --> Undefined property: App\Controllers\Nombre_motivos::$visitantes
#0 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 50)
#1 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->insertar()
#2 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-08-04 22:51:23 --> Invalid file: nombre_motivos/eliminados.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(35): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->eliminados()
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-08-04 22:54:40 --> Undefined array key "nombre_motivo_visita"
#0 C:\xampp\htdocs\visitas\app\Views\nombre_motivos\eliminados.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 26)
#1 C:\xampp\htdocs\visitas\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\visitas\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#4 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(35): view('nombre_motivos/...', Array)
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->eliminados()
#6 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#7 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-08-04 22:57:22 --> Invalid file: nombre_motivos/editar.php
#0 C:\xampp\htdocs\visitas\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nombre_motivos/...')
#1 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#2 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(60): view('nombre_motivos/...', Array)
#3 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->editar('2')
#4 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-08-04 23:00:29 --> Undefined array key "nombre_motivo_visita"
#0 C:\xampp\htdocs\visitas\app\Views\nombre_motivos\editar.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 11)
#1 C:\xampp\htdocs\visitas\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\visitas\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\visitas\system\Common.php(1089): CodeIgniter\View\View->render('nombre_motivos/...', Array, true)
#4 C:\xampp\htdocs\visitas\app\Controllers\Nombre_motivos.php(60): view('nombre_motivos/...', Array)
#5 C:\xampp\htdocs\visitas\system\CodeIgniter.php(832): App\Controllers\Nombre_motivos->editar('2')
#6 C:\xampp\htdocs\visitas\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Nombre_motivos))
#7 C:\xampp\htdocs\visitas\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\visitas\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
